import { Generated, Insertable, Selectable, Updateable } from 'kysely'


export interface Database {
  project: ProjectTable
}

export interface ProjectTable {
  // Columns that are generated by the database should be marked
  // using the `Generated` type. This way they are automatically
  // made optional in inserts and updates.
  id: Generated<string>

  name: string
  version: string
  public: boolean
  description: string | null
}

export type Project = Selectable<ProjectTable>
export type NewProject = Insertable<ProjectTable>
export type ProjectUpdate = Updateable<ProjectTable>
